### ISSUE TITLE
Installing Prime-Ubuntu-18.04

### ISSUE THREAD

**Issue by linux-man** [timrichardson/Prime-Ubuntu-18.04#6]
Since no one knows how long it will take to release [Bug #1778011](https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/1778011) on Bionic, I tried your solution with success.
The only strangeness I found was that powertop still show a 100% use of Nvidia, but my battery last a lot longer (>2x).
Because I like simple things, I created a basic install/uninstall script with a previously compiled prime_socket.
It was compiled/used on Mint 19 64.
It doesn't test if Nvidia is the actual driver.
It doesn't install lightdm.
It has a lot of drawbacks, but it's easy to use, so I'm uploading in case someone is interested.

Thank you all for the hard work.

[Prime-Mint-19.zip](https://github.com/timrichardson/Prime-Ubuntu-18.04/files/2349979/Prime-Mint-19.zip)

**Comment by timrichardson** [comment]
thanks. Bug #1778011 is being worked on. The card is turned off now with a technique much closer to the pre 18.04 approach, so it should work mostly everywhere it used to work. But the solution doesn't work with gdm3 (for me) and it doesn't work very well with lightdm either, so it's not ready for actual use. gdm3 has upstream bugs, I think Optimus users will need to use lightdm for some time. 
so far the work is only in 18.10; it will be a while before it arrives in 18.04 (if ever)

I'm closing this issue because this is not the place to add alternative versions. You may wish to contribute to to the thread on the nvidia developers linux topic.
